# Generated by Django 5.0.4 on 2024-07-03 07:15

import main_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=main_app.models.StudentIDField(default=1),
            preserve_default=False,
        ),
    ]
