# Generated by Django 5.0.4 on 2024-07-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_hotel_room_regularreservation_specialreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='total_guest',
            new_name='total_guests',
        ),
    ]
