# Generated by Django 5.0.4 on 2024-05-28 05:48

from django.db import migrations


def set_price(apps, schema_editor):
    MULTIPLIER = 120

    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all() # smartphone = ('apple', 0, 'No category')

    for smartphone in smartphones:
        smartphone.price = len(smartphone.brand) * MULTIPLIER

    smartphone_model.objects.bulk_update(smartphones, ['price'])


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        if smartphone.price < 750:
            smartphone.category = 'Cheap'
        else:
            smartphone.category = 'Expensive'

    smartphone_model.objects.bulk_update(smartphones, ['category'])


def set_to_default(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    default_price = smartphone_model._meta.get_field('price').default
    default_category = smartphone_model._meta.get_field('category').default

    for smartphone in smartphones:
        smartphone.price = default_price
        smartphone.category = default_category

    smartphone_model.objects.bulk_update(smartphones, ['price', 'category'])


def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reverse_code=set_to_default)
    ]
