# Generated by Django 4.2.4 on 2024-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='works_full_time',
            field=models.BooleanField(),
        ),
    ]
