# Generated by Django 5.0.4 on 2024-07-05 06:07

import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[main_app.validators.validate_phone_number]),
        ),
    ]
