# Generated by Django 4.2.4 on 2024-05-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_employee_works_full_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='months_of_employment',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February')], max_length=3, null=True),
        ),
    ]
